title: Welcome Visitor!
email: aniruddha200baidya@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I write code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "aniruddha200.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Aniruddha200

theme: jekyll-theme-minimal
